# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PMMP
title-bold: PocketMine
title-normal: MP
email: team@pmmp.io
description: Server software for Minecraft Pocket Edition written in PHP
baseurl: ""
url: "https://pmmp.io"
author: 
street_address:
city:
state:
zip_code:
country:
phone:

# Plugins
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions
#  - jekyll-sitemap
  - jekyll-feed

# Homepage tiles
#tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6
tiles-source: posts

# Social settings
500px_url: 
facebook_url: 
github_url: https://github.com/pmmp
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url: 
slack_url: 
twitter_url:

# Build settings
markdown: kramdown
